package com.giapnt.shoppingcart.postgresql.model;

/**
 * The Class Category.
 *
 * @author GiapNT
 */
@lombok.Data
public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.category.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.category.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.category.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.category.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.category.is_active
     *
     * @mbg.generated
     */
    private Integer isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.category.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.category.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.category.created_timestamp
     *
     * @mbg.generated
     */
    private String createdTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.category.updated_timestamp
     *
     * @mbg.generated
     */
    private String updatedTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.category.picture
     *
     * @mbg.generated
     */
    private byte[] picture;

}