package com.giapnt.shoppingcart.postgresql.model;

import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.order_subject
     *
     * @mbg.generated
     */
    private String orderSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.order_date
     *
     * @mbg.generated
     */
    private Date orderDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.ship_date
     *
     * @mbg.generated
     */
    private Date shipDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.required_date
     *
     * @mbg.generated
     */
    private Date requiredDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.freight
     *
     * @mbg.generated
     */
    private Integer freight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.sales_tax
     *
     * @mbg.generated
     */
    private Double salesTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.transaction_status
     *
     * @mbg.generated
     */
    private String transactionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.error_message
     *
     * @mbg.generated
     */
    private String errorMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.fulfilled
     *
     * @mbg.generated
     */
    private Integer fulfilled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.is_paid
     *
     * @mbg.generated
     */
    private Integer isPaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.payment_date
     *
     * @mbg.generated
     */
    private Date paymentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.is_active
     *
     * @mbg.generated
     */
    private Integer isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.created_timestamp
     *
     * @mbg.generated
     */
    private String createdTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.updated_timestamp
     *
     * @mbg.generated
     */
    private String updatedTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.shipper_id
     *
     * @mbg.generated
     */
    private Integer shipperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.payment_id
     *
     * @mbg.generated
     */
    private Integer paymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.id
     *
     * @return the value of public.orders.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.id
     *
     * @param id the value for public.orders.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.order_subject
     *
     * @return the value of public.orders.order_subject
     * @mbg.generated
     */
    public String getOrderSubject() {
        return orderSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.order_subject
     *
     * @param orderSubject the value for public.orders.order_subject
     * @mbg.generated
     */
    public void setOrderSubject(String orderSubject) {
        this.orderSubject = orderSubject == null ? null : orderSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.order_date
     *
     * @return the value of public.orders.order_date
     * @mbg.generated
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.order_date
     *
     * @param orderDate the value for public.orders.order_date
     * @mbg.generated
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.ship_date
     *
     * @return the value of public.orders.ship_date
     * @mbg.generated
     */
    public Date getShipDate() {
        return shipDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.ship_date
     *
     * @param shipDate the value for public.orders.ship_date
     * @mbg.generated
     */
    public void setShipDate(Date shipDate) {
        this.shipDate = shipDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.required_date
     *
     * @return the value of public.orders.required_date
     * @mbg.generated
     */
    public Date getRequiredDate() {
        return requiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.required_date
     *
     * @param requiredDate the value for public.orders.required_date
     * @mbg.generated
     */
    public void setRequiredDate(Date requiredDate) {
        this.requiredDate = requiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.freight
     *
     * @return the value of public.orders.freight
     * @mbg.generated
     */
    public Integer getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.freight
     *
     * @param freight the value for public.orders.freight
     * @mbg.generated
     */
    public void setFreight(Integer freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.sales_tax
     *
     * @return the value of public.orders.sales_tax
     * @mbg.generated
     */
    public Double getSalesTax() {
        return salesTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.sales_tax
     *
     * @param salesTax the value for public.orders.sales_tax
     * @mbg.generated
     */
    public void setSalesTax(Double salesTax) {
        this.salesTax = salesTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.transaction_status
     *
     * @return the value of public.orders.transaction_status
     * @mbg.generated
     */
    public String getTransactionStatus() {
        return transactionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.transaction_status
     *
     * @param transactionStatus the value for public.orders.transaction_status
     * @mbg.generated
     */
    public void setTransactionStatus(String transactionStatus) {
        this.transactionStatus = transactionStatus == null ? null : transactionStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.error_message
     *
     * @return the value of public.orders.error_message
     * @mbg.generated
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.error_message
     *
     * @param errorMessage the value for public.orders.error_message
     * @mbg.generated
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage == null ? null : errorMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.fulfilled
     *
     * @return the value of public.orders.fulfilled
     * @mbg.generated
     */
    public Integer getFulfilled() {
        return fulfilled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.fulfilled
     *
     * @param fulfilled the value for public.orders.fulfilled
     * @mbg.generated
     */
    public void setFulfilled(Integer fulfilled) {
        this.fulfilled = fulfilled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.is_paid
     *
     * @return the value of public.orders.is_paid
     * @mbg.generated
     */
    public Integer getIsPaid() {
        return isPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.is_paid
     *
     * @param isPaid the value for public.orders.is_paid
     * @mbg.generated
     */
    public void setIsPaid(Integer isPaid) {
        this.isPaid = isPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.payment_date
     *
     * @return the value of public.orders.payment_date
     * @mbg.generated
     */
    public Date getPaymentDate() {
        return paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.payment_date
     *
     * @param paymentDate the value for public.orders.payment_date
     * @mbg.generated
     */
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.is_active
     *
     * @return the value of public.orders.is_active
     * @mbg.generated
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.is_active
     *
     * @param isActive the value for public.orders.is_active
     * @mbg.generated
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.created_by
     *
     * @return the value of public.orders.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.created_by
     *
     * @param createdBy the value for public.orders.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.updated_by
     *
     * @return the value of public.orders.updated_by
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.updated_by
     *
     * @param updatedBy the value for public.orders.updated_by
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.created_timestamp
     *
     * @return the value of public.orders.created_timestamp
     * @mbg.generated
     */
    public Date getCreatedTimestamp() {
        return createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.created_timestamp
     *
     * @param createdTimestamp the value for public.orders.created_timestamp
     * @mbg.generated
     */
    public void setCreatedTimestamp(String createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.updated_timestamp
     *
     * @return the value of public.orders.updated_timestamp
     * @mbg.generated
     */
    public Date getUpdatedTimestamp() {
        return updatedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.updated_timestamp
     *
     * @param updatedTimestamp the value for public.orders.updated_timestamp
     * @mbg.generated
     */
    public void setUpdatedTimestamp(String updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.shipper_id
     *
     * @return the value of public.orders.shipper_id
     * @mbg.generated
     */
    public Integer getShipperId() {
        return shipperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.shipper_id
     *
     * @param shipperId the value for public.orders.shipper_id
     * @mbg.generated
     */
    public void setShipperId(Integer shipperId) {
        this.shipperId = shipperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.payment_id
     *
     * @return the value of public.orders.payment_id
     * @mbg.generated
     */
    public Integer getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.payment_id
     *
     * @param paymentId the value for public.orders.payment_id
     * @mbg.generated
     */
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.orders.user_id
     *
     * @return the value of public.orders.user_id
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.orders.user_id
     *
     * @param userId the value for public.orders.user_id
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}