package com.giapnt.shoppingcart.postgresql.model;

import lombok.Data;

import java.util.Date;

/**
 * The Class Order.
 *
 * @author GiapNT
 */
@Data
public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.order_subject
     *
     * @mbg.generated
     */
    private String orderSubject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.order_date
     *
     * @mbg.generated
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.ship_date
     *
     * @mbg.generated
     */
    private Date shipDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.required_date
     *
     * @mbg.generated
     */
    private Date requiredDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.freight
     *
     * @mbg.generated
     */
    private Integer freight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.sales_tax
     *
     * @mbg.generated
     */
    private Double salesTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.transaction_status
     *
     * @mbg.generated
     */
    private String transactionStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.error_message
     *
     * @mbg.generated
     */
    private String errorMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.fulfilled
     *
     * @mbg.generated
     */
    private Integer fulfilled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.is_paid
     *
     * @mbg.generated
     */
    private Integer isPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.payment_date
     *
     * @mbg.generated
     */
    private Date paymentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.is_active
     *
     * @mbg.generated
     */
    private Integer isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.created_timestamp
     *
     * @mbg.generated
     */
    private String createdTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.updated_timestamp
     *
     * @mbg.generated
     */
    private String updatedTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.shipper_id
     *
     * @mbg.generated
     */
    private Integer shipperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.payment_id
     *
     * @mbg.generated
     */
    private Integer paymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.orders.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

}