package com.giapnt.shoppingcart.postgresql.model;

import java.util.Date;
@lombok.Data
public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.order_number
     *
     * @mbg.generated
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.order_date
     *
     * @mbg.generated
     */
    private Date orderDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.ship_date
     *
     * @mbg.generated
     */
    private Date shipDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.required_date
     *
     * @mbg.generated
     */
    private Date requiredDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.freight
     *
     * @mbg.generated
     */
    private Integer freight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.sales_tax
     *
     * @mbg.generated
     */
    private Double salesTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.transaction_status
     *
     * @mbg.generated
     */
    private String transactionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.error_loc
     *
     * @mbg.generated
     */
    private String errorLoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.error_message
     *
     * @mbg.generated
     */
    private String errorMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.fulfilled
     *
     * @mbg.generated
     */
    private Integer fulfilled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.isdeleted
     *
     * @mbg.generated
     */
    private Integer isdeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.ispaid
     *
     * @mbg.generated
     */
    private Integer ispaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.payment_date
     *
     * @mbg.generated
     */
    private Date paymentDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.created_timestamp
     *
     * @mbg.generated
     */
    private String createdTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.updated_timestamp
     *
     * @mbg.generated
     */
    private String updatedTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.shipper_id
     *
     * @mbg.generated
     */
    private Long shipperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.payment_id
     *
     * @mbg.generated
     */
    private Long paymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.orders.user_id
     *
     * @mbg.generated
     */
    private Long userId;


}