package com.giapnt.shoppingcart.postgresql.model;

import lombok.Data;

/**
 * The Class Payment.
 *
 * @author GiapNT
 */
@Data
public class Payment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.payment.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.payment.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.payment.allowed
     *
     * @mbg.generated
     */
    private Integer allowed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.payment.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.payment.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.payment.created_timestamp
     *
     * @mbg.generated
     */
    private String createdTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.payment.updated_timestamp
     *
     * @mbg.generated
     */
    private String updatedTimestamp;

}