package com.giapnt.shoppingcart.postgresql.model;

import lombok.Data;

@Data
public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.product_available
     *
     * @mbg.generated
     */
    private Integer productAvailable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.unit_price
     *
     * @mbg.generated
     */
    private Double unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.quantity_per_unit
     *
     * @mbg.generated
     */
    private Integer quantityPerUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.sizes
     *
     * @mbg.generated
     */
    private Integer sizes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.unit_weight
     *
     * @mbg.generated
     */
    private Double unitWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.unit_in_stock
     *
     * @mbg.generated
     */
    private Long unitInStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.unit_on_order
     *
     * @mbg.generated
     */
    private Integer unitOnOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.discount_available
     *
     * @mbg.generated
     */
    private Integer discountAvailable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.discount
     *
     * @mbg.generated
     */
    private Double discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.ranking
     *
     * @mbg.generated
     */
    private String ranking;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.is_active
     *
     * @mbg.generated
     */
    private Integer isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.created_timestamp
     *
     * @mbg.generated
     */
    private String createdTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.updated_timestamp
     *
     * @mbg.generated
     */
    private String updatedTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.supplier_id
     *
     * @mbg.generated
     */
    private Long supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.picture
     *
     * @mbg.generated
     */
    private byte[] picture;

}