package com.giapnt.shoppingcart.postgresql.model;

@lombok.Data
public class Products {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.sku
     *
     * @mbg.generated
     */
    private Long sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.sku_id
     *
     * @mbg.generated
     */
    private Long skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.vendor_product_id
     *
     * @mbg.generated
     */
    private Long vendorProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.quantity_per_unit
     *
     * @mbg.generated
     */
    private Integer quantityPerUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.unit_price
     *
     * @mbg.generated
     */
    private Double unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.msrp
     *
     * @mbg.generated
     */
    private Double msrp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.available_size
     *
     * @mbg.generated
     */
    private Integer availableSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.available_color
     *
     * @mbg.generated
     */
    private String availableColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.sizes
     *
     * @mbg.generated
     */
    private Integer sizes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.discount
     *
     * @mbg.generated
     */
    private Double discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.unit_weight
     *
     * @mbg.generated
     */
    private Double unitWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.unit_in_stock
     *
     * @mbg.generated
     */
    private Long unitInStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.unit_on_order
     *
     * @mbg.generated
     */
    private Integer unitOnOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.re_order_level
     *
     * @mbg.generated
     */
    private Integer reOrderLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.product_available
     *
     * @mbg.generated
     */
    private Integer productAvailable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.discount_available
     *
     * @mbg.generated
     */
    private Integer discountAvailable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.current_order
     *
     * @mbg.generated
     */
    private String currentOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.ranking
     *
     * @mbg.generated
     */
    private String ranking;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.created_timestamp
     *
     * @mbg.generated
     */
    private String createdTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.updated_timestamp
     *
     * @mbg.generated
     */
    private String updatedTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.supplier_id
     *
     * @mbg.generated
     */
    private Long supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.products.picture
     *
     * @mbg.generated
     */
    private byte[] picture;

}