package com.giapnt.shoppingcart.postgresql.model;

import lombok.Data;

/**
 * The Class Role.
 *
 * @author GiapNT
 */
@Data
public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.role.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.role.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.role.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.role.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.role.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.role.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.role.isactive
     *
     * @mbg.generated
     */
    private Long isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.role.created_timestamp
     *
     * @mbg.generated
     */
    private String createdTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.role.updated_timestamp
     *
     * @mbg.generated
     */
    private String updatedTimestamp;

}