package com.giapnt.shoppingcart.postgresql.model;

@lombok.Data
public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.role.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.role.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.role.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.role.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.role.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.role.created_timestamp
     *
     * @mbg.generated
     */
    private String createdTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.role.updated_timestamp
     *
     * @mbg.generated
     */
    private String updatedTimestamp;

}