package com.giapnt.shoppingcart.postgresql.model;

import java.util.Date;

public class Shippers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.isactive
     *
     * @mbg.generated
     */
    private Long isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.created_timestamp
     *
     * @mbg.generated
     */
    private String createdTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.updated_timestamp
     *
     * @mbg.generated
     */
    private String updatedTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shippers.id
     *
     * @return the value of public.shippers.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shippers.id
     *
     * @param id the value for public.shippers.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shippers.code
     *
     * @return the value of public.shippers.code
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shippers.code
     *
     * @param code the value for public.shippers.code
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shippers.name
     *
     * @return the value of public.shippers.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shippers.name
     *
     * @param name the value for public.shippers.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shippers.phone
     *
     * @return the value of public.shippers.phone
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shippers.phone
     *
     * @param phone the value for public.shippers.phone
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shippers.description
     *
     * @return the value of public.shippers.description
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shippers.description
     *
     * @param description the value for public.shippers.description
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shippers.created_by
     *
     * @return the value of public.shippers.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shippers.created_by
     *
     * @param createdBy the value for public.shippers.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shippers.updated_by
     *
     * @return the value of public.shippers.updated_by
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shippers.updated_by
     *
     * @param updatedBy the value for public.shippers.updated_by
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shippers.isactive
     *
     * @return the value of public.shippers.isactive
     * @mbg.generated
     */
    public Long getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shippers.isactive
     *
     * @param isactive the value for public.shippers.isactive
     * @mbg.generated
     */
    public void setIsactive(Long isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shippers.created_timestamp
     *
     * @return the value of public.shippers.created_timestamp
     * @mbg.generated
     */
    public Date getCreatedTimestamp() {
        return createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shippers.created_timestamp
     *
     * @param createdTimestamp the value for public.shippers.created_timestamp
     * @mbg.generated
     */
    public void setCreatedTimestamp(String createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shippers.updated_timestamp
     *
     * @return the value of public.shippers.updated_timestamp
     * @mbg.generated
     */
    public Date getUpdatedTimestamp() {
        return updatedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shippers.updated_timestamp
     *
     * @param updatedTimestamp the value for public.shippers.updated_timestamp
     * @mbg.generated
     */
    public void setUpdatedTimestamp(String updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }
}