package com.giapnt.shoppingcart.postgresql.model;

import lombok.Data;

/**
 * The Class Shipper.
 *
 * @author GiapNT
 */
@Data
public class Shipper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.isactive
     *
     * @mbg.generated
     */
    private int isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.created_timestamp
     *
     * @mbg.generated
     */
    private String createdTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shippers.updated_timestamp
     *
     * @mbg.generated
     */
    private String updatedTimestamp;
}