package com.giapnt.shoppingcart.postgresql.model;

import java.util.Date;

public class Suppliers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.payment_methods
     *
     * @mbg.generated
     */
    private String paymentMethods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.type_goods
     *
     * @mbg.generated
     */
    private String typeGoods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.discount_type
     *
     * @mbg.generated
     */
    private String discountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.discount_available
     *
     * @mbg.generated
     */
    private Integer discountAvailable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.current_order
     *
     * @mbg.generated
     */
    private String currentOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.notes
     *
     * @mbg.generated
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.is_active
     *
     * @mbg.generated
     */
    private Integer isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.created_timestamp
     *
     * @mbg.generated
     */
    private String createdTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.updated_timestamp
     *
     * @mbg.generated
     */
    private String updatedTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.id
     *
     * @return the value of public.suppliers.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.id
     *
     * @param id the value for public.suppliers.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.name
     *
     * @return the value of public.suppliers.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.name
     *
     * @param name the value for public.suppliers.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.code
     *
     * @return the value of public.suppliers.code
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.code
     *
     * @param code the value for public.suppliers.code
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.address
     *
     * @return the value of public.suppliers.address
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.address
     *
     * @param address the value for public.suppliers.address
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.city
     *
     * @return the value of public.suppliers.city
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.city
     *
     * @param city the value for public.suppliers.city
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.country
     *
     * @return the value of public.suppliers.country
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.country
     *
     * @param country the value for public.suppliers.country
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.phone
     *
     * @return the value of public.suppliers.phone
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.phone
     *
     * @param phone the value for public.suppliers.phone
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.email
     *
     * @return the value of public.suppliers.email
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.email
     *
     * @param email the value for public.suppliers.email
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.url
     *
     * @return the value of public.suppliers.url
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.url
     *
     * @param url the value for public.suppliers.url
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.payment_methods
     *
     * @return the value of public.suppliers.payment_methods
     * @mbg.generated
     */
    public String getPaymentMethods() {
        return paymentMethods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.payment_methods
     *
     * @param paymentMethods the value for public.suppliers.payment_methods
     * @mbg.generated
     */
    public void setPaymentMethods(String paymentMethods) {
        this.paymentMethods = paymentMethods == null ? null : paymentMethods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.type_goods
     *
     * @return the value of public.suppliers.type_goods
     * @mbg.generated
     */
    public String getTypeGoods() {
        return typeGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.type_goods
     *
     * @param typeGoods the value for public.suppliers.type_goods
     * @mbg.generated
     */
    public void setTypeGoods(String typeGoods) {
        this.typeGoods = typeGoods == null ? null : typeGoods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.discount_type
     *
     * @return the value of public.suppliers.discount_type
     * @mbg.generated
     */
    public String getDiscountType() {
        return discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.discount_type
     *
     * @param discountType the value for public.suppliers.discount_type
     * @mbg.generated
     */
    public void setDiscountType(String discountType) {
        this.discountType = discountType == null ? null : discountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.discount_available
     *
     * @return the value of public.suppliers.discount_available
     * @mbg.generated
     */
    public Integer getDiscountAvailable() {
        return discountAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.discount_available
     *
     * @param discountAvailable the value for public.suppliers.discount_available
     * @mbg.generated
     */
    public void setDiscountAvailable(Integer discountAvailable) {
        this.discountAvailable = discountAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.current_order
     *
     * @return the value of public.suppliers.current_order
     * @mbg.generated
     */
    public String getCurrentOrder() {
        return currentOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.current_order
     *
     * @param currentOrder the value for public.suppliers.current_order
     * @mbg.generated
     */
    public void setCurrentOrder(String currentOrder) {
        this.currentOrder = currentOrder == null ? null : currentOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.notes
     *
     * @return the value of public.suppliers.notes
     * @mbg.generated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.notes
     *
     * @param notes the value for public.suppliers.notes
     * @mbg.generated
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.is_active
     *
     * @return the value of public.suppliers.is_active
     * @mbg.generated
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.is_active
     *
     * @param isActive the value for public.suppliers.is_active
     * @mbg.generated
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.created_by
     *
     * @return the value of public.suppliers.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.created_by
     *
     * @param createdBy the value for public.suppliers.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.updated_by
     *
     * @return the value of public.suppliers.updated_by
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.updated_by
     *
     * @param updatedBy the value for public.suppliers.updated_by
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.created_timestamp
     *
     * @return the value of public.suppliers.created_timestamp
     * @mbg.generated
     */
    public Date getCreatedTimestamp() {
        return createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.created_timestamp
     *
     * @param createdTimestamp the value for public.suppliers.created_timestamp
     * @mbg.generated
     */
    public void setCreatedTimestamp(String createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.updated_timestamp
     *
     * @return the value of public.suppliers.updated_timestamp
     * @mbg.generated
     */
    public Date getUpdatedTimestamp() {
        return updatedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.suppliers.updated_timestamp
     *
     * @param updatedTimestamp the value for public.suppliers.updated_timestamp
     * @mbg.generated
     */
    public void setUpdatedTimestamp(String updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }
}