package com.giapnt.shoppingcart.postgresql.model;

@lombok.Data
public class Suppliers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.company_first_name
     *
     * @mbg.generated
     */
    private String companyFirstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.contact_last_name
     *
     * @mbg.generated
     */
    private String contactLastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.contact_title
     *
     * @mbg.generated
     */
    private String contactTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.address1
     *
     * @mbg.generated
     */
    private String address1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.address2
     *
     * @mbg.generated
     */
    private String address2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.address3
     *
     * @mbg.generated
     */
    private String address3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.postal_code
     *
     * @mbg.generated
     */
    private String postalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.fax
     *
     * @mbg.generated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.payment_methods
     *
     * @mbg.generated
     */
    private String paymentMethods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.discount_type
     *
     * @mbg.generated
     */
    private String discountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.type_goods
     *
     * @mbg.generated
     */
    private String typeGoods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.notes
     *
     * @mbg.generated
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.discount_available
     *
     * @mbg.generated
     */
    private Integer discountAvailable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.current_order
     *
     * @mbg.generated
     */
    private String currentOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.size_url
     *
     * @mbg.generated
     */
    private Integer sizeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.size_url
     *
     * @mbg.generated
     */
    private Integer isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.created_timestamp
     *
     * @mbg.generated
     */
    private String createdTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.updated_timestamp
     *
     * @mbg.generated
     */
    private String updatedTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.suppliers.id
     *
     * @return the value of public.suppliers.id
     *
     * @mbg.generated
     */
}