package com.giapnt.shoppingcart.postgresql.model;

import lombok.Data;

@Data
public class Supplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.payment_methods
     *
     * @mbg.generated
     */
    private String paymentMethods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.type_goods
     *
     * @mbg.generated
     */
    private String typeGoods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.discount_type
     *
     * @mbg.generated
     */
    private String discountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.discount_available
     *
     * @mbg.generated
     */
    private Integer discountAvailable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.current_order
     *
     * @mbg.generated
     */
    private String currentOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.notes
     *
     * @mbg.generated
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.is_active
     *
     * @mbg.generated
     */
    private Integer isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.created_timestamp
     *
     * @mbg.generated
     */
    private String createdTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.suppliers.updated_timestamp
     *
     * @mbg.generated
     */
    private String updatedTimestamp;

}