package com.giapnt.shoppingcart.postgresql.model;

import java.util.Date;

public class Suppliers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.company_first_name
     *
     * @mbg.generated
     */
    private String companyFirstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.contact_last_name
     *
     * @mbg.generated
     */
    private String contactLastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.contact_title
     *
     * @mbg.generated
     */
    private String contactTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.address1
     *
     * @mbg.generated
     */
    private String address1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.address2
     *
     * @mbg.generated
     */
    private String address2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.address3
     *
     * @mbg.generated
     */
    private String address3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.postal_code
     *
     * @mbg.generated
     */
    private String postalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.fax
     *
     * @mbg.generated
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.payment_methods
     *
     * @mbg.generated
     */
    private String paymentMethods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.discount_type
     *
     * @mbg.generated
     */
    private String discountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.type_goods
     *
     * @mbg.generated
     */
    private String typeGoods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.notes
     *
     * @mbg.generated
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.discount_available
     *
     * @mbg.generated
     */
    private Integer discountAvailable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.current_order
     *
     * @mbg.generated
     */
    private String currentOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.size_url
     *
     * @mbg.generated
     */
    private Integer sizeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.created_timestamp
     *
     * @mbg.generated
     */
    private Date createdTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_data.suppliers.updated_timestamp
     *
     * @mbg.generated
     */
    private Date updatedTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.id
     *
     * @return the value of core_data.suppliers.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.id
     *
     * @param id the value for core_data.suppliers.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.company_first_name
     *
     * @return the value of core_data.suppliers.company_first_name
     *
     * @mbg.generated
     */
    public String getCompanyFirstName() {
        return companyFirstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.company_first_name
     *
     * @param companyFirstName the value for core_data.suppliers.company_first_name
     *
     * @mbg.generated
     */
    public void setCompanyFirstName(String companyFirstName) {
        this.companyFirstName = companyFirstName == null ? null : companyFirstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.contact_last_name
     *
     * @return the value of core_data.suppliers.contact_last_name
     *
     * @mbg.generated
     */
    public String getContactLastName() {
        return contactLastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.contact_last_name
     *
     * @param contactLastName the value for core_data.suppliers.contact_last_name
     *
     * @mbg.generated
     */
    public void setContactLastName(String contactLastName) {
        this.contactLastName = contactLastName == null ? null : contactLastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.contact_title
     *
     * @return the value of core_data.suppliers.contact_title
     *
     * @mbg.generated
     */
    public String getContactTitle() {
        return contactTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.contact_title
     *
     * @param contactTitle the value for core_data.suppliers.contact_title
     *
     * @mbg.generated
     */
    public void setContactTitle(String contactTitle) {
        this.contactTitle = contactTitle == null ? null : contactTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.address1
     *
     * @return the value of core_data.suppliers.address1
     *
     * @mbg.generated
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.address1
     *
     * @param address1 the value for core_data.suppliers.address1
     *
     * @mbg.generated
     */
    public void setAddress1(String address1) {
        this.address1 = address1 == null ? null : address1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.address2
     *
     * @return the value of core_data.suppliers.address2
     *
     * @mbg.generated
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.address2
     *
     * @param address2 the value for core_data.suppliers.address2
     *
     * @mbg.generated
     */
    public void setAddress2(String address2) {
        this.address2 = address2 == null ? null : address2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.address3
     *
     * @return the value of core_data.suppliers.address3
     *
     * @mbg.generated
     */
    public String getAddress3() {
        return address3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.address3
     *
     * @param address3 the value for core_data.suppliers.address3
     *
     * @mbg.generated
     */
    public void setAddress3(String address3) {
        this.address3 = address3 == null ? null : address3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.city
     *
     * @return the value of core_data.suppliers.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.city
     *
     * @param city the value for core_data.suppliers.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.country
     *
     * @return the value of core_data.suppliers.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.country
     *
     * @param country the value for core_data.suppliers.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.postal_code
     *
     * @return the value of core_data.suppliers.postal_code
     *
     * @mbg.generated
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.postal_code
     *
     * @param postalCode the value for core_data.suppliers.postal_code
     *
     * @mbg.generated
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode == null ? null : postalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.phone
     *
     * @return the value of core_data.suppliers.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.phone
     *
     * @param phone the value for core_data.suppliers.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.fax
     *
     * @return the value of core_data.suppliers.fax
     *
     * @mbg.generated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.fax
     *
     * @param fax the value for core_data.suppliers.fax
     *
     * @mbg.generated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.email
     *
     * @return the value of core_data.suppliers.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.email
     *
     * @param email the value for core_data.suppliers.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.url
     *
     * @return the value of core_data.suppliers.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.url
     *
     * @param url the value for core_data.suppliers.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.payment_methods
     *
     * @return the value of core_data.suppliers.payment_methods
     *
     * @mbg.generated
     */
    public String getPaymentMethods() {
        return paymentMethods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.payment_methods
     *
     * @param paymentMethods the value for core_data.suppliers.payment_methods
     *
     * @mbg.generated
     */
    public void setPaymentMethods(String paymentMethods) {
        this.paymentMethods = paymentMethods == null ? null : paymentMethods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.discount_type
     *
     * @return the value of core_data.suppliers.discount_type
     *
     * @mbg.generated
     */
    public String getDiscountType() {
        return discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.discount_type
     *
     * @param discountType the value for core_data.suppliers.discount_type
     *
     * @mbg.generated
     */
    public void setDiscountType(String discountType) {
        this.discountType = discountType == null ? null : discountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.type_goods
     *
     * @return the value of core_data.suppliers.type_goods
     *
     * @mbg.generated
     */
    public String getTypeGoods() {
        return typeGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.type_goods
     *
     * @param typeGoods the value for core_data.suppliers.type_goods
     *
     * @mbg.generated
     */
    public void setTypeGoods(String typeGoods) {
        this.typeGoods = typeGoods == null ? null : typeGoods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.notes
     *
     * @return the value of core_data.suppliers.notes
     *
     * @mbg.generated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.notes
     *
     * @param notes the value for core_data.suppliers.notes
     *
     * @mbg.generated
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.discount_available
     *
     * @return the value of core_data.suppliers.discount_available
     *
     * @mbg.generated
     */
    public Integer getDiscountAvailable() {
        return discountAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.discount_available
     *
     * @param discountAvailable the value for core_data.suppliers.discount_available
     *
     * @mbg.generated
     */
    public void setDiscountAvailable(Integer discountAvailable) {
        this.discountAvailable = discountAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.current_order
     *
     * @return the value of core_data.suppliers.current_order
     *
     * @mbg.generated
     */
    public String getCurrentOrder() {
        return currentOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.current_order
     *
     * @param currentOrder the value for core_data.suppliers.current_order
     *
     * @mbg.generated
     */
    public void setCurrentOrder(String currentOrder) {
        this.currentOrder = currentOrder == null ? null : currentOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.customer_id
     *
     * @return the value of core_data.suppliers.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.customer_id
     *
     * @param customerId the value for core_data.suppliers.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.size_url
     *
     * @return the value of core_data.suppliers.size_url
     *
     * @mbg.generated
     */
    public Integer getSizeUrl() {
        return sizeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.size_url
     *
     * @param sizeUrl the value for core_data.suppliers.size_url
     *
     * @mbg.generated
     */
    public void setSizeUrl(Integer sizeUrl) {
        this.sizeUrl = sizeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.created_by
     *
     * @return the value of core_data.suppliers.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.created_by
     *
     * @param createdBy the value for core_data.suppliers.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.updated_by
     *
     * @return the value of core_data.suppliers.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.updated_by
     *
     * @param updatedBy the value for core_data.suppliers.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.created_timestamp
     *
     * @return the value of core_data.suppliers.created_timestamp
     *
     * @mbg.generated
     */
    public Date getCreatedTimestamp() {
        return createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.created_timestamp
     *
     * @param createdTimestamp the value for core_data.suppliers.created_timestamp
     *
     * @mbg.generated
     */
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_data.suppliers.updated_timestamp
     *
     * @return the value of core_data.suppliers.updated_timestamp
     *
     * @mbg.generated
     */
    public Date getUpdatedTimestamp() {
        return updatedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_data.suppliers.updated_timestamp
     *
     * @param updatedTimestamp the value for core_data.suppliers.updated_timestamp
     *
     * @mbg.generated
     */
    public void setUpdatedTimestamp(Date updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }
}