package com.giapnt.shoppingcart.postgresql.model;

import java.util.Date;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.credit_card
     *
     * @mbg.generated
     */
    private String creditCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.credit_card_type_id
     *
     * @mbg.generated
     */
    private Integer creditCardTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.card_exp_mo
     *
     * @mbg.generated
     */
    private String cardExpMo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.card_exp_yr
     *
     * @mbg.generated
     */
    private String cardExpYr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.billing_address
     *
     * @mbg.generated
     */
    private String billingAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.billing_city
     *
     * @mbg.generated
     */
    private String billingCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.billing_country
     *
     * @mbg.generated
     */
    private String billingCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.ship_address
     *
     * @mbg.generated
     */
    private String shipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.ship_city
     *
     * @mbg.generated
     */
    private String shipCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.ship_country
     *
     * @mbg.generated
     */
    private String shipCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.date_entered
     *
     * @mbg.generated
     */
    private Date dateEntered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.is_active
     *
     * @mbg.generated
     */
    private Integer isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.created_timestamp
     *
     * @mbg.generated
     */
    private String createdTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.updated_timestamp
     *
     * @mbg.generated
     */
    private String updatedTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.id
     *
     * @return the value of public.users.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.id
     *
     * @param id the value for public.users.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.code
     *
     * @return the value of public.users.code
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.code
     *
     * @param code the value for public.users.code
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.first_name
     *
     * @return the value of public.users.first_name
     * @mbg.generated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.first_name
     *
     * @param firstName the value for public.users.first_name
     * @mbg.generated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.last_name
     *
     * @return the value of public.users.last_name
     * @mbg.generated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.last_name
     *
     * @param lastName the value for public.users.last_name
     * @mbg.generated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.address
     *
     * @return the value of public.users.address
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.address
     *
     * @param address the value for public.users.address
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.city
     *
     * @return the value of public.users.city
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.city
     *
     * @param city the value for public.users.city
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.country
     *
     * @return the value of public.users.country
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.country
     *
     * @param country the value for public.users.country
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.phone
     *
     * @return the value of public.users.phone
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.phone
     *
     * @param phone the value for public.users.phone
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.email
     *
     * @return the value of public.users.email
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.email
     *
     * @param email the value for public.users.email
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.password
     *
     * @return the value of public.users.password
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.password
     *
     * @param password the value for public.users.password
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.credit_card
     *
     * @return the value of public.users.credit_card
     * @mbg.generated
     */
    public String getCreditCard() {
        return creditCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.credit_card
     *
     * @param creditCard the value for public.users.credit_card
     * @mbg.generated
     */
    public void setCreditCard(String creditCard) {
        this.creditCard = creditCard == null ? null : creditCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.credit_card_type_id
     *
     * @return the value of public.users.credit_card_type_id
     * @mbg.generated
     */
    public Integer getCreditCardTypeId() {
        return creditCardTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.credit_card_type_id
     *
     * @param creditCardTypeId the value for public.users.credit_card_type_id
     * @mbg.generated
     */
    public void setCreditCardTypeId(Integer creditCardTypeId) {
        this.creditCardTypeId = creditCardTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.card_exp_mo
     *
     * @return the value of public.users.card_exp_mo
     * @mbg.generated
     */
    public String getCardExpMo() {
        return cardExpMo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.card_exp_mo
     *
     * @param cardExpMo the value for public.users.card_exp_mo
     * @mbg.generated
     */
    public void setCardExpMo(String cardExpMo) {
        this.cardExpMo = cardExpMo == null ? null : cardExpMo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.card_exp_yr
     *
     * @return the value of public.users.card_exp_yr
     * @mbg.generated
     */
    public String getCardExpYr() {
        return cardExpYr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.card_exp_yr
     *
     * @param cardExpYr the value for public.users.card_exp_yr
     * @mbg.generated
     */
    public void setCardExpYr(String cardExpYr) {
        this.cardExpYr = cardExpYr == null ? null : cardExpYr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.billing_address
     *
     * @return the value of public.users.billing_address
     * @mbg.generated
     */
    public String getBillingAddress() {
        return billingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.billing_address
     *
     * @param billingAddress the value for public.users.billing_address
     * @mbg.generated
     */
    public void setBillingAddress(String billingAddress) {
        this.billingAddress = billingAddress == null ? null : billingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.billing_city
     *
     * @return the value of public.users.billing_city
     * @mbg.generated
     */
    public String getBillingCity() {
        return billingCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.billing_city
     *
     * @param billingCity the value for public.users.billing_city
     * @mbg.generated
     */
    public void setBillingCity(String billingCity) {
        this.billingCity = billingCity == null ? null : billingCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.billing_country
     *
     * @return the value of public.users.billing_country
     * @mbg.generated
     */
    public String getBillingCountry() {
        return billingCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.billing_country
     *
     * @param billingCountry the value for public.users.billing_country
     * @mbg.generated
     */
    public void setBillingCountry(String billingCountry) {
        this.billingCountry = billingCountry == null ? null : billingCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.ship_address
     *
     * @return the value of public.users.ship_address
     * @mbg.generated
     */
    public String getShipAddress() {
        return shipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.ship_address
     *
     * @param shipAddress the value for public.users.ship_address
     * @mbg.generated
     */
    public void setShipAddress(String shipAddress) {
        this.shipAddress = shipAddress == null ? null : shipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.ship_city
     *
     * @return the value of public.users.ship_city
     * @mbg.generated
     */
    public String getShipCity() {
        return shipCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.ship_city
     *
     * @param shipCity the value for public.users.ship_city
     * @mbg.generated
     */
    public void setShipCity(String shipCity) {
        this.shipCity = shipCity == null ? null : shipCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.ship_country
     *
     * @return the value of public.users.ship_country
     * @mbg.generated
     */
    public String getShipCountry() {
        return shipCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.ship_country
     *
     * @param shipCountry the value for public.users.ship_country
     * @mbg.generated
     */
    public void setShipCountry(String shipCountry) {
        this.shipCountry = shipCountry == null ? null : shipCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.date_entered
     *
     * @return the value of public.users.date_entered
     * @mbg.generated
     */
    public Date getDateEntered() {
        return dateEntered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.date_entered
     *
     * @param dateEntered the value for public.users.date_entered
     * @mbg.generated
     */
    public void setDateEntered(Date dateEntered) {
        this.dateEntered = dateEntered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.is_active
     *
     * @return the value of public.users.is_active
     * @mbg.generated
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.is_active
     *
     * @param isActive the value for public.users.is_active
     * @mbg.generated
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.created_by
     *
     * @return the value of public.users.created_by
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.created_by
     *
     * @param createdBy the value for public.users.created_by
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.updated_by
     *
     * @return the value of public.users.updated_by
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.updated_by
     *
     * @param updatedBy the value for public.users.updated_by
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.created_timestamp
     *
     * @return the value of public.users.created_timestamp
     * @mbg.generated
     */
    public Date getCreatedTimestamp() {
        return createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.created_timestamp
     *
     * @param createdTimestamp the value for public.users.created_timestamp
     * @mbg.generated
     */
    public void setCreatedTimestamp(String createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.updated_timestamp
     *
     * @return the value of public.users.updated_timestamp
     * @mbg.generated
     */
    public Date getUpdatedTimestamp() {
        return updatedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.updated_timestamp
     *
     * @param updatedTimestamp the value for public.users.updated_timestamp
     * @mbg.generated
     */
    public void setUpdatedTimestamp(String updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }
}