package com.giapnt.shoppingcart.postgresql.mapper;

import com.giapnt.shoppingcart.postgresql.model.Category;

import java.util.List;

/**
 * The Interface CategoryMapper.
 *
 * @author GiapNT
 */
public interface CategoryMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.category
     *
     * @param id the id
     * @return the int
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.category
     *
     * @param record the record
     * @return the int
     * @mbg.generated
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.category
     *
     * @param id the id
     * @return the category
     * @mbg.generated
     */
    Category selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.category
     *
     * @return the list
     * @mbg.generated
     */
    List<Category> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.category
     *
     * @param record the record
     * @return the int
     * @mbg.generated
     */
    int updateByPrimaryKey(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core_data.category
     *
     * @param name the name
     * @return the long
     * @mbg.generated
     */
    long selectCheckName(String name);
}