package com.giapnt.shoppingcart.postgresql.mapper;

import com.giapnt.shoppingcart.postgresql.model.Payment;

import java.util.List;

public interface PaymentMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment
     *
     * @param id the id
     * @return the int
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment
     *
     * @param record the record
     * @return the int
     * @mbg.generated
     */
    int insert(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment
     *
     * @param id the id
     * @return the payment
     * @mbg.generated
     */
    Payment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment
     *
     * @return the list
     * @mbg.generated
     */
    List<Payment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment
     *
     * @param record the record
     * @return the int
     * @mbg.generated
     */
    int updateByPrimaryKey(Payment record);
}