package com.giapnt.shoppingcart.postgresql.mapper;

import com.giapnt.shoppingcart.postgresql.model.Products;

import java.util.List;

public interface ProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.products
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.products
     *
     * @mbg.generated
     */
    int insert(Products record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.products
     *
     * @mbg.generated
     */
    Products selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.products
     *
     * @mbg.generated
     */
    List<Products> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.products
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Products record);
}