package com.giapnt.shoppingcart.postgresql.mapper;

import com.giapnt.shoppingcart.postgresql.model.Shipper;

import java.util.List;

public interface ShippersMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shippers
     *
     * @param id the id
     * @return the int
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shippers
     *
     * @param record the record
     * @return the int
     * @mbg.generated
     */
    int insert(Shipper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shippers
     *
     * @param id the id
     * @return the shipper
     * @mbg.generated
     */
    Shipper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shippers
     *
     * @return the list
     * @mbg.generated
     */
    List<Shipper> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shippers
     *
     * @param record the record
     * @return the int
     * @mbg.generated
     */
    int updateByPrimaryKey(Shipper record);
}