package com.giapnt.shoppingcart.postgresql.mapper;

import com.giapnt.shoppingcart.postgresql.model.Suppliers;
import java.util.List;

public interface SuppliersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.suppliers
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.suppliers
     *
     * @mbg.generated
     */
    int insert(Suppliers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.suppliers
     *
     * @mbg.generated
     */
    Suppliers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.suppliers
     *
     * @mbg.generated
     */
    List<Suppliers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.suppliers
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Suppliers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.suppliers
     *
     * @mbg.generated
     */
    List<Suppliers> selectListIsActive(int isActive);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.suppliers
     *
     * @mbg.generated
     */
    int updateCurrentStatusByPrimaryKey(Suppliers record);
}