package com.giapnt.shoppingcart.postgresql.mapper;

import com.giapnt.shoppingcart.postgresql.model.Supplier;
import java.util.List;

public interface SupplierMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.suppliers
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.suppliers
	 *
	 * @mbg.generated
	 */
	int insert(Supplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.suppliers
	 *
	 * @mbg.generated
	 */
	Supplier selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.suppliers
	 *
	 * @mbg.generated
	 */
	List<Supplier> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.suppliers
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Supplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.suppliers
	 *
	 * @mbg.generated
	 */
	List<Supplier> selectListIsActive(int isActive);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table public.suppliers
	 *
	 * @mbg.generated
	 */
	int updateCurrentStatusByPrimaryKey(Supplier record);
}